### ISSUE TITLE
Error ".config/darktable/luarc:649: Module <unnamed module> is not compatible with API 6.0.0" when trying to start script-manager

### ISSUE THREAD

**Issue by dennis605** [wpferguson/script-manager#1]
I always get the mentioned error message when I try to start darktable with "Script Manager" enabled on my Macbook running 11.0.1. I could not get "Script Manager" get working on my Macbook. 
When I comment out the line 649 in file "luarc" it's working like a charm and the error message disappeared.
Maybe this can help someone else:
I changed from 
`dt.configuration.check_version(...,{5,0,0})`
to
`-- dt.configuration.check_version(...,{5,0,0})`

**Comment by wpferguson** [comment]
You might want to update your scripts from https://github.com/darktable-org/lua-scripts.git and then change your luarc file to 
`require "tools/script_manager"`.  This issue has been fixed for a couple of years (almost).  script_manager has also been rewritten to work better with darktable 3.4, https://discuss.pixls.us/t/for-a-new-darktable-a-new-script-manager

**Comment by dennis605** [comment]
Ah, perfect... Thank you for pointing this out. I updated the script and it is working perfect - thank you
